### ISSUE TITLE
[data.energystar.gov/ymjh-yrse] Question about "ENERGY STAR Certified Residential Refrigerators"

### ISSUE THREAD

**Issue by suiza** [socrata/discuss#23]
API Docs: https://dev.socrata.com/foundry/data.energystar.gov/ymjh-yrse

Hello there,

We are using our approved token but there is still a threshold of product count on the response, 1000 limit. We are using the following URL to extract over 1500 refrigerators:

https://data.energystar.gov/resource/ymjh-yrse.csv?&&app_token={invisible_token_here}

Thank you very much in ahead,

Danny Suiza

**Comment by shua123** [comment]
I think you'll need to include $limit=2000 (or whatever limit you want) in your URL otherwise it defaults to 1000.

**Comment by shua123** [comment]
@chrismetcalf It might be useful to include the default limit on the dataset API docs page? I'm not sure its clear that one should click the Paging through Data link to see the default limit. Also maybe add the default limit to the limit documentation page (https://dev.socrata.com/docs/queries/limit.html).

**Comment by suiza** [comment]
Excellent. Thank you very much. It works and now I know also that the limit is 50000 (https://dev.socrata.com/docs/paging.html#2.1)

**Comment by chrismetcalf** [comment]
@shua123 Thanks for jumping in and helping!

@suiza Actually, if you're really using a v2.1 API ([which it looks like you are](https://dev.socrata.com/foundry/data.energystar.gov/ymjh-yrse)), the limit is actually raised. See the [`$limit`](https://dev.socrata.com/docs/queries/limit.html) docs to learn more.

Since that's a bit unclear, I've filed a bug to update that page: https://github.com/socrata/dev.socrata.com/issues/545
