### ISSUE TITLE
404 Trying to Access Nova Scotia Civic Address File

### ISSUE THREAD

**Issue by KirbyMyers** [socrata/discuss#34]
I believe it's actually a problem with the data source itself and not my code, but where this is my first time trying out Socrata, I was hoping someone could confirm.  You'll notice you can't even use the "try it" function here:
https://dev.socrata.com/foundry/data.novascotia.ca/tntn-er5g

**Comment by chrismetcalf** [comment]
Looks like you somehow ended up on the documentation page for a "map" visualization, instead of the dataset that actually powers it. If I may ask, what link did you follow to get there? I have [an open issue](https://github.com/socrata/dev.socrata.com/issues/475) to better handle it when people end up there, sounds like I need to bump the priority of that.

For now, you'll be better off with the [endpoint for the data layer](https://dev.socrata.com/foundry/data.novascotia.ca/y2vi-7kwq) for that dataset. Let me know if that works better for you.

**Comment by KirbyMyers** [comment]
I found it through the Province's Open Data page here.  If you search catalog for Civic Address, it should be the top option 'Nova Scotia Civic Address File - Civic Points'.
https://data.novascotia.ca/browse?q=civic&sortBy=relevance&utf8=%E2%9C%93

Thanks very much; I'll try that new link and get back to you.

**Comment by KirbyMyers** [comment]
PS:  That new link works fine to access the data source.  Thanks!
