### ISSUE TITLE
[data.iowa.gov/gq4y-pik4] Question about "Food Assistance Program Households Recipients and Allotments by Month and County"

### ISSUE THREAD

**Issue by C00222130** [socrata/discuss#46]
API Docs: https://dev.socrata.com/foundry/data.iowa.gov/gq4y-pik4

Hi guys.
With respect to the new downloadable version of the CSV file the row containing primary_county_coordinates  is concatenated as primary_county_long and then primary_county_lat
Should it not read primary_county_lat then primary_county_long.
If you agree and are planning to fix , could you also include a comma between the coordinates also. It would make mapping easier when pulling into Folium
[FAPRev1.txt](https://github.com/socrata/discuss/files/815993/FAPRev1.txt)

**Comment by chrismetcalf** [comment]
@C00222130 The `primary_county_coordinates` column is actually a geospatial [`Point`](https://dev.socrata.com/docs/datatypes/point.html#,) column. In the CSV output type, it is encoded as a [Well-Known Text `POINT`](https://en.wikipedia.org/wiki/Well-known_text) record, a commonly-used format for geospatial data. They're actually ordered as "long, lat" (X, Y) since that's the standard used by geographers and GIS experts.

In your case, I'd recommend instead using the `primary_county_lat` and `primary_county_long` columns, which contain the same data broken out as their own fields. If you need them concatenated into a single field, you could use a `$select` statement to concatenate them yourself, like:

`GET https://data.iowa.gov/resource/gq4y-pik4.json?$select=*, primary_county_lat || "," || primary_county_long AS coordinates`
